// Generated by CoffeeScript 1.6.2
(function() {
  (function(clock) {
    "use strict";    return clock.SelectorView = (function() {
      function SelectorView(scope, dispatcher) {
        var views;

        views = {
          digital: clock.DigitalView,
          analog: clock.AnalogView,
          polar: clock.PolarView
        };
        scope.select = function(event, id) {
          return dispatcher.dispatch('create', views[id]);
        };
      }

      return SelectorView;

    })();
  })(window.clock = window.clock || {});

}).call(this);
